/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.api;

import com.transferzero.sdk.ApiException;
import com.transferzero.sdk.model.DebitListResponse;
import com.transferzero.sdk.model.DebitRequestWrapper;
import com.transferzero.sdk.model.DebitResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AccountDebitsApi
 */
@Ignore
public class AccountDebitsApiTest {

    private final AccountDebitsApi api = new AccountDebitsApi();

    
    /**
     * Fetching an account debit
     *
     * Returns a single account debit by the account debit ID
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountsDebitTest() throws ApiException {
        UUID accountDebitID = null;
        DebitResponse response = api.getAccountsDebit(accountDebitID);

        // TODO: test validations
    }
    
    /**
     * Listing Accounts debits
     *
     * Get a list of accounts debits
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountsDebitsTest() throws ApiException {
        Integer page = null;
        Integer per = null;
        DebitListResponse response = api.getAccountsDebits(page, per);

        // TODO: test validations
    }
    
    /**
     * Creating an account debit
     *
     * Creates a new account debit finding transaction through the internal balance  To successfully fund a transaction - - The currency needs to be the same as the input_currency on the transaction - The amount has to be the same as the input_amount on the transaction - The to_id is the id of the transaction - You need to have enough balance of the appropriate currency inside your wallet  Once the transaction is funded, we will immediately start trying to pay out the recipient(s).  It is also possible to create multiple account debits by supplying an array of debit objects 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postAccountsDebitsTest() throws ApiException {
        DebitRequestWrapper debitRequestWrapper = null;
        DebitListResponse response = api.postAccountsDebits(debitRequestWrapper);

        // TODO: test validations
    }
    
}
