/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.api;

import com.transferzero.sdk.ApiException;
import com.transferzero.sdk.model.ApiLogListResponse;
import com.transferzero.sdk.model.ApiLogResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiLogsApi
 */
@Ignore
public class ApiLogsApiTest {

    private final ApiLogsApi api = new ApiLogsApi();

    
    /**
     * Fetch an individual API log
     *
     * Returns a single API log based on the API log ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApiLogTest() throws ApiException {
        UUID apILogID = null;
        ApiLogResponse response = api.getApiLog(apILogID);

        // TODO: test validations
    }
    
    /**
     * Fetch a list of API logs
     *
     * Returns a list of API logs. Also includes information relating to the original request.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getApiLogsTest() throws ApiException {
        Integer page = null;
        Integer per = null;
        String createdAtFrom = null;
        String createdAtTo = null;
        ApiLogListResponse response = api.getApiLogs(page, per, createdAtFrom, createdAtTo);

        // TODO: test validations
    }
    
}
