/*
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.api;

import com.transferzero.sdk.ApiException;
import com.transferzero.sdk.model.BankAccountDetailsResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BankAccountDetailsApi
 */
@Ignore
public class BankAccountDetailsApiTest {

    private final BankAccountDetailsApi api = new BankAccountDetailsApi();

    
    /**
     * Fetching bank account details
     *
     * Returns single bank account details based on the currency
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBankAccountDetailsTest() throws ApiException {
        String currency = null;
        BankAccountDetailsResponse response = api.getBankAccountDetails(currency)
                .execute();

        // TODO: test validations
    }
    
}
