/*
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.api;

import com.transferzero.sdk.ApiException;
import com.transferzero.sdk.model.OpenCorporatesSupportedCountriesListResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OpenCorporatesSupportedCountriesApi
 */
@Ignore
public class OpenCorporatesSupportedCountriesApiTest {

    private final OpenCorporatesSupportedCountriesApi api = new OpenCorporatesSupportedCountriesApi();

    
    /**
     * Get List of Supported Countries from OpenCorporates
     *
     * Get List of Supported Countries from OpenCorporates
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getOpenCorporatesSupportedCountriesTest() throws ApiException {
        OpenCorporatesSupportedCountriesListResponse response = api.getOpenCorporatesSupportedCountries()
                .execute();

        // TODO: test validations
    }
    
}
