/*
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.api;

import com.transferzero.sdk.ApiException;
import com.transferzero.sdk.model.OpenCorporatesSearchRequest;
import com.transferzero.sdk.model.OpenCorporatesSearchResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OpenCorporatesCompanySearchApi
 */
@Ignore
public class OpenCorporatesCompanySearchApiTest {

    private final OpenCorporatesCompanySearchApi api = new OpenCorporatesCompanySearchApi();

    
    /**
     * Search for a company on Open Corporates
     *
     * This endpoint searches for a company on Open Corporates API and returns the name if found
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchCompanyTest() throws ApiException {
        OpenCorporatesSearchRequest openCorporatesSearchRequest = null;
        OpenCorporatesSearchResponse response = api.searchCompany(openCorporatesSearchRequest);

        // TODO: test validations
    }
    
}
