/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Currency
 */
public class CurrencyTest {
    private final Currency model = new Currency();

    /**
     * Model tests for Currency
     */
    @Test
    public void testCurrency() {
        // TODO: test Currency
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'decimals'
     */
    @Test
    public void decimalsTest() {
        // TODO: test decimals
    }

    /**
     * Test the property 'subunitToUnit'
     */
    @Test
    public void subunitToUnitTest() {
        // TODO: test subunitToUnit
    }

    /**
     * Test the property 'primary'
     */
    @Test
    public void primaryTest() {
        // TODO: test primary
    }

    /**
     * Test the property 'min'
     */
    @Test
    public void minTest() {
        // TODO: test min
    }

    /**
     * Test the property 'max'
     */
    @Test
    public void maxTest() {
        // TODO: test max
    }

    /**
     * Test the property 'margin'
     */
    @Test
    public void marginTest() {
        // TODO: test margin
    }

    /**
     * Test the property 'usdEquivalent'
     */
    @Test
    public void usdEquivalentTest() {
        // TODO: test usdEquivalent
    }

}
