/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.transferzero.sdk.model.Debit;
import com.transferzero.sdk.model.DebitListRequest;
import com.transferzero.sdk.model.DebitRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DebitRequestWrapper
 */
public class DebitRequestWrapperTest {
    private final DebitRequestWrapper model = new DebitRequestWrapper();

    /**
     * Model tests for DebitRequestWrapper
     */
    @Test
    public void testDebitRequestWrapper() {
        // TODO: test DebitRequestWrapper
    }

}
