/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayinMethodDetailsBTC
 */
public class PayinMethodDetailsBTCTest {
    private final PayinMethodDetailsBTC model = new PayinMethodDetailsBTC();

    /**
     * Model tests for PayinMethodDetailsBTC
     */
    @Test
    public void testPayinMethodDetailsBTC() {
        // TODO: test PayinMethodDetailsBTC
    }

    /**
     * Test the property 'refundAddress'
     */
    @Test
    public void refundAddressTest() {
        // TODO: test refundAddress
    }

}
