/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.transferzero.sdk.model.PayinMethodDetails;
import com.transferzero.sdk.model.PayinMethodState;
import com.transferzero.sdk.model.PayinMethodUxFlow;
import com.transferzero.sdk.model.StateReasonDetails;
import com.transferzero.sdk.model.ValidationErrorDescription;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayinMethod
 */
public class PayinMethodTest {
    private final PayinMethod model = new PayinMethod();

    /**
     * Model tests for PayinMethod
     */
    @Test
    public void testPayinMethod() {
        // TODO: test PayinMethod
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'uxFlow'
     */
    @Test
    public void uxFlowTest() {
        // TODO: test uxFlow
    }

    /**
     * Test the property 'inDetails'
     */
    @Test
    public void inDetailsTest() {
        // TODO: test inDetails
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'stateReasonDetails'
     */
    @Test
    public void stateReasonDetailsTest() {
        // TODO: test stateReasonDetails
    }

    /**
     * Test the property 'outDetails'
     */
    @Test
    public void outDetailsTest() {
        // TODO: test outDetails
    }

    /**
     * Test the property 'instructions'
     */
    @Test
    public void instructionsTest() {
        // TODO: test instructions
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

}
