/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.transferzero.sdk.model.PayoutMethodMobileProviderEnum;
import com.transferzero.sdk.model.PayoutMethodTransferReasonEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayoutMethodDetailsGHSMobile
 */
public class PayoutMethodDetailsGHSMobileTest {
    private final PayoutMethodDetailsGHSMobile model = new PayoutMethodDetailsGHSMobile();

    /**
     * Model tests for PayoutMethodDetailsGHSMobile
     */
    @Test
    public void testPayoutMethodDetailsGHSMobile() {
        // TODO: test PayoutMethodDetailsGHSMobile
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'mobileProvider'
     */
    @Test
    public void mobileProviderTest() {
        // TODO: test mobileProvider
    }

    /**
     * Test the property 'transferReason'
     */
    @Test
    public void transferReasonTest() {
        // TODO: test transferReason
    }

}
