/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayoutMethodCashProviderEnum
 */
public class PayoutMethodCashProviderEnumTest {
    /**
     * Model tests for PayoutMethodCashProviderEnum
     */
    @Test
    public void testPayoutMethodCashProviderEnum() {
        // TODO: test PayoutMethodCashProviderEnum
    }

}
