/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.transferzero.sdk.model.PayoutMethodGenderEnum;
import com.transferzero.sdk.model.PayoutMethodIdentityCardTypeEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayoutMethodDetailsMADCash
 */
public class PayoutMethodDetailsMADCashTest {
    private final PayoutMethodDetailsMADCash model = new PayoutMethodDetailsMADCash();

    /**
     * Model tests for PayoutMethodDetailsMADCash
     */
    @Test
    public void testPayoutMethodDetailsMADCash() {
        // TODO: test PayoutMethodDetailsMADCash
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'senderIdentityCardType'
     */
    @Test
    public void senderIdentityCardTypeTest() {
        // TODO: test senderIdentityCardType
    }

    /**
     * Test the property 'senderIdentityCardId'
     */
    @Test
    public void senderIdentityCardIdTest() {
        // TODO: test senderIdentityCardId
    }

    /**
     * Test the property 'senderCityOfBirth'
     */
    @Test
    public void senderCityOfBirthTest() {
        // TODO: test senderCityOfBirth
    }

    /**
     * Test the property 'senderCountryOfBirth'
     */
    @Test
    public void senderCountryOfBirthTest() {
        // TODO: test senderCountryOfBirth
    }

    /**
     * Test the property 'senderGender'
     */
    @Test
    public void senderGenderTest() {
        // TODO: test senderGender
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'identityCardType'
     */
    @Test
    public void identityCardTypeTest() {
        // TODO: test identityCardType
    }

    /**
     * Test the property 'identityCardId'
     */
    @Test
    public void identityCardIdTest() {
        // TODO: test identityCardId
    }

}
