/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.transferzero.sdk.model.PayoutMethodBankAccountTypeEnum;
import com.transferzero.sdk.model.PayoutMethodCashProviderEnum;
import com.transferzero.sdk.model.PayoutMethodCountryEnumUSDBank;
import com.transferzero.sdk.model.PayoutMethodDetailsBTC;
import com.transferzero.sdk.model.PayoutMethodDetailsBalance;
import com.transferzero.sdk.model.PayoutMethodDetailsGBPBank;
import com.transferzero.sdk.model.PayoutMethodDetailsGHSBank;
import com.transferzero.sdk.model.PayoutMethodDetailsGHSCash;
import com.transferzero.sdk.model.PayoutMethodDetailsIBAN;
import com.transferzero.sdk.model.PayoutMethodDetailsKESBank;
import com.transferzero.sdk.model.PayoutMethodDetailsKESMobile;
import com.transferzero.sdk.model.PayoutMethodDetailsMADCash;
import com.transferzero.sdk.model.PayoutMethodDetailsMobile;
import com.transferzero.sdk.model.PayoutMethodDetailsNGNBank;
import com.transferzero.sdk.model.PayoutMethodDetailsUSDBank;
import com.transferzero.sdk.model.PayoutMethodDetailsXOFBank;
import com.transferzero.sdk.model.PayoutMethodDetailsXOFCash;
import com.transferzero.sdk.model.PayoutMethodDetailsXOFMobile;
import com.transferzero.sdk.model.PayoutMethodDetailsZARBank;
import com.transferzero.sdk.model.PayoutMethodGenderEnum;
import com.transferzero.sdk.model.PayoutMethodIdentityCardTypeEnum;
import com.transferzero.sdk.model.PayoutMethodLegalEntityTypeEnum;
import com.transferzero.sdk.model.PayoutMethodMobileProviderEnum;
import com.transferzero.sdk.model.PayoutMethodNatureOfBusinessEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayoutMethodDetails
 */
public class PayoutMethodDetailsTest {
    private final PayoutMethodDetails model = new PayoutMethodDetails();

    /**
     * Model tests for PayoutMethodDetails
     */
    @Test
    public void testPayoutMethodDetails() {
        // TODO: test PayoutMethodDetails
    }

}
