/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.transferzero.sdk.model.PayoutMethodCountryEnumUSDBank;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayoutMethodDetailsUSDBank
 */
public class PayoutMethodDetailsUSDBankTest {
    private final PayoutMethodDetailsUSDBank model = new PayoutMethodDetailsUSDBank();

    /**
     * Model tests for PayoutMethodDetailsUSDBank
     */
    @Test
    public void testPayoutMethodDetailsUSDBank() {
        // TODO: test PayoutMethodDetailsUSDBank
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    public void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'bankCode'
     */
    @Test
    public void bankCodeTest() {
        // TODO: test bankCode
    }

    /**
     * Test the property 'bankAccount'
     */
    @Test
    public void bankAccountTest() {
        // TODO: test bankAccount
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

}
