/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.transferzero.sdk.model.PayoutMethodIdentityCardTypeEnum;
import com.transferzero.sdk.model.PayoutMethodTransferReasonEnum;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PayoutMethodDetailsKESBank
 */
public class PayoutMethodDetailsKESBankTest {
    private final PayoutMethodDetailsKESBank model = new PayoutMethodDetailsKESBank();

    /**
     * Model tests for PayoutMethodDetailsKESBank
     */
    @Test
    public void testPayoutMethodDetailsKESBank() {
        // TODO: test PayoutMethodDetailsKESBank
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'street'
     */
    @Test
    public void streetTest() {
        // TODO: test street
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'bankCode'
     */
    @Test
    public void bankCodeTest() {
        // TODO: test bankCode
    }

    /**
     * Test the property 'bankAccount'
     */
    @Test
    public void bankAccountTest() {
        // TODO: test bankAccount
    }

    /**
     * Test the property 'transferReason'
     */
    @Test
    public void transferReasonTest() {
        // TODO: test transferReason
    }

    /**
     * Test the property 'identityCardType'
     */
    @Test
    public void identityCardTypeTest() {
        // TODO: test identityCardType
    }

    /**
     * Test the property 'identityCardId'
     */
    @Test
    public void identityCardIdTest() {
        // TODO: test identityCardId
    }

    /**
     * Test the property 'relationshipToSender'
     */
    @Test
    public void relationshipToSenderTest() {
        // TODO: test relationshipToSender
    }

}
