/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Describes the account holder name on a successful match
 */
@ApiModel(description = "Describes the account holder name on a successful match")

public class AccountValidationResult {
  public static final String SERIALIZED_NAME_ACCOUNT_NAME = "account_name";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_NAME)
  private String accountName;

  public static final String SERIALIZED_NAME_MAPPED_MOBILE_PROVIDER = "mapped_mobile_provider";
  @SerializedName(SERIALIZED_NAME_MAPPED_MOBILE_PROVIDER)
  private String mappedMobileProvider;

   /**
   * Get accountName
   * @return accountName
  **/
  @ApiModelProperty(example = "John Smith", value = "")
  public String getAccountName() {
    return accountName;
  }

   /**
   * Get mappedMobileProvider
   * @return mappedMobileProvider
  **/
  @ApiModelProperty(example = "mtn", value = "")
  public String getMappedMobileProvider() {
    return mappedMobileProvider;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountValidationResult accountValidationResult = (AccountValidationResult) o;
    return Objects.equals(this.accountName, accountValidationResult.accountName) &&
        Objects.equals(this.mappedMobileProvider, accountValidationResult.mappedMobileProvider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountName, mappedMobileProvider);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountValidationResult {\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    mappedMobileProvider: ").append(toIndentedString(mappedMobileProvider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

