/*
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * EntityCreateRequest
 */

public class EntityCreateRequest {
  public static final String SERIALIZED_NAME_ENTITY_ID = "entity_id";
  @SerializedName(SERIALIZED_NAME_ENTITY_ID)
  private UUID entityId;

  public static final String SERIALIZED_NAME_ENTITY_TYPE = "entity_type";
  @SerializedName(SERIALIZED_NAME_ENTITY_TYPE)
  private String entityType;

  public static final String SERIALIZED_NAME_AUTOMATED_FIELDS = "automated_fields";
  @SerializedName(SERIALIZED_NAME_AUTOMATED_FIELDS)
  private Object automatedFields = null;

  public EntityCreateRequest entityId(UUID entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Id of linked entity
   * @return entityId
  **/
  @ApiModelProperty(example = "86912555-272a-48f7-bdbb-eab653150e01", value = "Id of linked entity")
  public UUID getEntityId() {
    return entityId;
  }

  public void setEntityId(UUID entityId) {
    this.entityId = entityId;
  }

  public EntityCreateRequest entityType(String entityType) {
    this.entityType = entityType;
    return this;
  }

   /**
   * Type of entity to create eg Sender, Company 
   * @return entityType
  **/
  @ApiModelProperty(value = "Type of entity to create eg Sender, Company ")
  public String getEntityType() {
    return entityType;
  }

  public void setEntityType(String entityType) {
    this.entityType = entityType;
  }

  public EntityCreateRequest automatedFields(Object automatedFields) {
    this.automatedFields = automatedFields;
    return this;
  }

   /**
   * Attributes needed to calculate the risk scores for the automated fields
   * @return automatedFields
  **/
  @ApiModelProperty(example = "{\"financial_institution\":\"true\",\"financial_regulator\":\"\",\"regulatory_licence_number\":\"\",\"amount_monthly_transactions\":\"Above $500,000\",\"country_of_incorporation\":\"AF\",\"trading_country\":\"US\",\"shareholders_nationalities\":[\"AF\",\"GB\",\"IT\"],\"directors_nationalities\":[\"AU\",\"BE\",\"GM\"],\"directors_residences\":[\"AR\",\"HK\",\"SS\"],\"sanction_check_state\":\"1\"}", value = "Attributes needed to calculate the risk scores for the automated fields")
  public Object getAutomatedFields() {
    return automatedFields;
  }

  public void setAutomatedFields(Object automatedFields) {
    this.automatedFields = automatedFields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityCreateRequest entityCreateRequest = (EntityCreateRequest) o;
    return Objects.equals(this.entityId, entityCreateRequest.entityId) &&
        Objects.equals(this.entityType, entityCreateRequest.entityType) &&
        Objects.equals(this.automatedFields, entityCreateRequest.automatedFields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityId, entityType, automatedFields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityCreateRequest {\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    entityType: ").append(toIndentedString(entityType)).append("\n");
    sb.append("    automatedFields: ").append(toIndentedString(automatedFields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

