/*
 * BitPesa Private API
 * API specification used for internal BitPesa endpoints
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The state of the entity. Can be one of the following:  - &#x60;incomplete&#x60;: When an entity has not been submitted with required details - &#x60;complete&#x60;: When an entity is created and has all the required details
 */
@JsonAdapter(EntityState.Adapter.class)
public enum EntityState {
  
  INCOMPLETE("incomplete"),
  
  COMPLETE("complete");

  private String value;

  EntityState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EntityState fromValue(String value) {
    for (EntityState b : EntityState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EntityState> {
    @Override
    public void write(final JsonWriter jsonWriter, final EntityState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EntityState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EntityState.fromValue(value);
    }
  }
}

