/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Current state of the mandate.  * &#x60;pending&#x60; — created, awaiting signing flow * &#x60;notified&#x60; — recipient has been notified to sign * &#x60;signed&#x60; — recipient signed; mandate is active * &#x60;failed&#x60; — signing flow failed (e.g. AVS/CDV rejection) * &#x60;bypassed&#x60; — administratively bypassed for an inward AZA payment
 */
@JsonAdapter(MandateStatus.Adapter.class)
public enum MandateStatus {
  
  PENDING("pending"),
  
  NOTIFIED("notified"),
  
  SIGNED("signed"),
  
  FAILED("failed"),
  
  BYPASSED("bypassed");

  private String value;

  MandateStatus(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MandateStatus fromValue(String value) {
    for (MandateStatus b : MandateStatus.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<MandateStatus> {
    @Override
    public void write(final JsonWriter jsonWriter, final MandateStatus enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MandateStatus read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MandateStatus.fromValue(value);
    }
  }
}

