/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * &#x60;&#x60;&#x60;JSON   \&quot;details\&quot;: {     \&quot;refund_address\&quot;: \&quot;n4VQ5YdHf7hLQ2gWQYYrcxoE5B7nWuDFNF\&quot;   } &#x60;&#x60;&#x60;
 */
@ApiModel(description = "```JSON   \"details\": {     \"refund_address\": \"n4VQ5YdHf7hLQ2gWQYYrcxoE5B7nWuDFNF\"   } ```")

public class PayinMethodDetailsBTC {
  public static final String SERIALIZED_NAME_REFUND_ADDRESS = "refund_address";
  @SerializedName(SERIALIZED_NAME_REFUND_ADDRESS)
  private String refundAddress;

  public PayinMethodDetailsBTC refundAddress(String refundAddress) {
    this.refundAddress = refundAddress;
    return this;
  }

   /**
   * Please make sure the refund_address is a valid BTC address belonging to the sender, as that is going to be used in case the transaction has to be refunded.
   * @return refundAddress
  **/
  @ApiModelProperty(value = "Please make sure the refund_address is a valid BTC address belonging to the sender, as that is going to be used in case the transaction has to be refunded.")
  public String getRefundAddress() {
    return refundAddress;
  }

  public void setRefundAddress(String refundAddress) {
    this.refundAddress = refundAddress;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PayinMethodDetailsBTC payinMethodDetailsBTC = (PayinMethodDetailsBTC) o;
    return Objects.equals(this.refundAddress, payinMethodDetailsBTC.refundAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(refundAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PayinMethodDetailsBTC {\n");
    sb.append("    refundAddress: ").append(toIndentedString(refundAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

