/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The country for USD::Bank payouts.  Valid options are: - NG
 */
@JsonAdapter(PayoutMethodCountryEnumUSDBank.Adapter.class)
public enum PayoutMethodCountryEnumUSDBank {
  
  NG("NG");

  private String value;

  PayoutMethodCountryEnumUSDBank(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PayoutMethodCountryEnumUSDBank fromValue(String value) {
    for (PayoutMethodCountryEnumUSDBank b : PayoutMethodCountryEnumUSDBank.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PayoutMethodCountryEnumUSDBank> {
    @Override
    public void write(final JsonWriter jsonWriter, final PayoutMethodCountryEnumUSDBank enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PayoutMethodCountryEnumUSDBank read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PayoutMethodCountryEnumUSDBank.fromValue(value);
    }
  }
}

