/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The country for the pickup or mobile payout.  For USD cash pickup in Nigeria, valid options are: - &#x60;NG&#x60;: Nigeria  For XOF cash pickup, valid options are: - &#x60;CI&#x60;: Ivory Coast - &#x60;ML&#x60;: Mali - &#x60;SN&#x60;: Senegal  For XOF mobile payout, valid options are: - &#x60;CI&#x60;: Ivory Coast - &#x60;SN&#x60;: Senegal - &#x60;BF&#x60;: Burkina Faso - &#x60;ML&#x60;: Mali  For XAF mobile payout, valid options are: - &#x60;CM&#x60;: Cameroon
 */
@JsonAdapter(PayoutMethodCountryEnum.Adapter.class)
public enum PayoutMethodCountryEnum {
  
  AF("AF"),
  
  AL("AL"),
  
  DZ("DZ"),
  
  AS("AS"),
  
  AD("AD"),
  
  AO("AO"),
  
  AI("AI"),
  
  AQ("AQ"),
  
  AG("AG"),
  
  AR("AR"),
  
  AM("AM"),
  
  AW("AW"),
  
  AX("AX"),
  
  AU("AU"),
  
  AT("AT"),
  
  AZ("AZ"),
  
  BS("BS"),
  
  BH("BH"),
  
  BD("BD"),
  
  BB("BB"),
  
  BY("BY"),
  
  BE("BE"),
  
  BZ("BZ"),
  
  BJ("BJ"),
  
  BM("BM"),
  
  BT("BT"),
  
  BO("BO"),
  
  BA("BA"),
  
  BW("BW"),
  
  BV("BV"),
  
  BR("BR"),
  
  IO("IO"),
  
  BN("BN"),
  
  BG("BG"),
  
  BF("BF"),
  
  BI("BI"),
  
  KH("KH"),
  
  CM("CM"),
  
  CA("CA"),
  
  CV("CV"),
  
  KY("KY"),
  
  CF("CF"),
  
  TD("TD"),
  
  CL("CL"),
  
  CN("CN"),
  
  CX("CX"),
  
  CC("CC"),
  
  CO("CO"),
  
  KM("KM"),
  
  CG("CG"),
  
  CD("CD"),
  
  CK("CK"),
  
  CR("CR"),
  
  CI("CI"),
  
  HR("HR"),
  
  CU("CU"),
  
  CY("CY"),
  
  CZ("CZ"),
  
  DK("DK"),
  
  DJ("DJ"),
  
  DM("DM"),
  
  DO("DO"),
  
  TP("TP"),
  
  EC("EC"),
  
  EG("EG"),
  
  SV("SV"),
  
  GQ("GQ"),
  
  ER("ER"),
  
  EE("EE"),
  
  ET("ET"),
  
  FK("FK"),
  
  FO("FO"),
  
  FJ("FJ"),
  
  FI("FI"),
  
  FR("FR"),
  
  GF("GF"),
  
  PF("PF"),
  
  TF("TF"),
  
  GA("GA"),
  
  GM("GM"),
  
  GE("GE"),
  
  DE("DE"),
  
  GH("GH"),
  
  GI("GI"),
  
  GR("GR"),
  
  GL("GL"),
  
  GD("GD"),
  
  GP("GP"),
  
  GU("GU"),
  
  GT("GT"),
  
  GN("GN"),
  
  GW("GW"),
  
  GY("GY"),
  
  HT("HT"),
  
  HM("HM"),
  
  VA("VA"),
  
  HN("HN"),
  
  HK("HK"),
  
  HU("HU"),
  
  IS("IS"),
  
  IN("IN"),
  
  ID("ID"),
  
  IR("IR"),
  
  IQ("IQ"),
  
  IE("IE"),
  
  IL("IL"),
  
  IT("IT"),
  
  JM("JM"),
  
  JP("JP"),
  
  JO("JO"),
  
  KZ("KZ"),
  
  KE("KE"),
  
  KI("KI"),
  
  KP("KP"),
  
  KR("KR"),
  
  KV("KV"),
  
  KW("KW"),
  
  KG("KG"),
  
  LA("LA"),
  
  LV("LV"),
  
  LB("LB"),
  
  LS("LS"),
  
  LR("LR"),
  
  LY("LY"),
  
  LI("LI"),
  
  LT("LT"),
  
  LU("LU"),
  
  MO("MO"),
  
  MK("MK"),
  
  MG("MG"),
  
  MW("MW"),
  
  MY("MY"),
  
  MV("MV"),
  
  ML("ML"),
  
  MT("MT"),
  
  MH("MH"),
  
  MQ("MQ"),
  
  MR("MR"),
  
  MU("MU"),
  
  YT("YT"),
  
  MX("MX"),
  
  FM("FM"),
  
  MD("MD"),
  
  MC("MC"),
  
  MN("MN"),
  
  MS("MS"),
  
  ME("ME"),
  
  MA("MA"),
  
  MZ("MZ"),
  
  MM("MM"),
  
  NA("NA"),
  
  NR("NR"),
  
  NP("NP"),
  
  NL("NL"),
  
  AN("AN"),
  
  NC("NC"),
  
  NZ("NZ"),
  
  NI("NI"),
  
  NE("NE"),
  
  NG("NG"),
  
  NU("NU"),
  
  NF("NF"),
  
  MP("MP"),
  
  NO("NO"),
  
  OM("OM"),
  
  PK("PK"),
  
  PW("PW"),
  
  PS("PS"),
  
  PA("PA"),
  
  PG("PG"),
  
  PY("PY"),
  
  PE("PE"),
  
  PH("PH"),
  
  PN("PN"),
  
  PL("PL"),
  
  PT("PT"),
  
  PR("PR"),
  
  QA("QA"),
  
  RE("RE"),
  
  RO("RO"),
  
  RU("RU"),
  
  RW("RW"),
  
  SH("SH"),
  
  KN("KN"),
  
  LC("LC"),
  
  PM("PM"),
  
  VC("VC"),
  
  WS("WS"),
  
  SM("SM"),
  
  ST("ST"),
  
  SA("SA"),
  
  SN("SN"),
  
  RS("RS"),
  
  SC("SC"),
  
  SL("SL"),
  
  SG("SG"),
  
  SK("SK"),
  
  SI("SI"),
  
  SB("SB"),
  
  SO("SO"),
  
  ZA("ZA"),
  
  GS("GS"),
  
  ES("ES"),
  
  LK("LK"),
  
  SD("SD"),
  
  SR("SR"),
  
  SJ("SJ"),
  
  SZ("SZ"),
  
  SE("SE"),
  
  CH("CH"),
  
  SY("SY"),
  
  TW("TW"),
  
  TJ("TJ"),
  
  TZ("TZ"),
  
  TH("TH"),
  
  TG("TG"),
  
  TK("TK"),
  
  TO("TO"),
  
  TT("TT"),
  
  TN("TN"),
  
  TR("TR"),
  
  TM("TM"),
  
  TC("TC"),
  
  TV("TV"),
  
  UG("UG"),
  
  UA("UA"),
  
  AE("AE"),
  
  GB("GB"),
  
  US("US"),
  
  UM("UM"),
  
  UY("UY"),
  
  UZ("UZ"),
  
  VU("VU"),
  
  VE("VE"),
  
  VN("VN"),
  
  VG("VG"),
  
  VI("VI"),
  
  WF("WF"),
  
  EH("EH"),
  
  YE("YE"),
  
  ZM("ZM");

  private String value;

  PayoutMethodCountryEnum(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PayoutMethodCountryEnum fromValue(String value) {
    for (PayoutMethodCountryEnum b : PayoutMethodCountryEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PayoutMethodCountryEnum> {
    @Override
    public void write(final JsonWriter jsonWriter, final PayoutMethodCountryEnum enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PayoutMethodCountryEnum read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PayoutMethodCountryEnum.fromValue(value);
    }
  }
}

