/*
 * TransferZero API
 * Reference documentation for the TransferZero API V1
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.transferzero.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Metadata related to the webhook response
 */
@ApiModel(description = "Metadata related to the webhook response")

public class WebhookLogMetadataResponse {
  public static final String SERIALIZED_NAME_BODY = "body";
  @SerializedName(SERIALIZED_NAME_BODY)
  private String body;

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  private Map<String, String> headers = null;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;


   /**
   * Full body of response
   * @return body
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "<!DOCTYPE html> <html lang=\"en\"> <head> <meta charset=\"utf-8\" /> <title>Action Controller: Exception caught</title>", value = "Full body of response")

  public String getBody() {
    return body;
  }




   /**
   * Headers delivered with webhook response
   * @return headers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"date\":\"Fri, 11 Jan 2019 09:00:00 GMT\",\"connection\":\"close\",\"content-type\":\"text/html; charset=utf-8\",\"x-web-console-session-id\":\"a0696374-de2f-4b4e-a2d7-cb4e0a1240c0\",\"x-web-console-mount-point\":\"/__web_console\",\"x-request-id\":\"a0696374-de2f-4b4e-a2d7-cb4e0a1240c0\",\"x-runtime\":\"0.484015\",\"content-length\":\"145453\"}", value = "Headers delivered with webhook response")

  public Map<String, String> getHeaders() {
    return headers;
  }




   /**
   * Status of response
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "500", value = "Status of response")

  public String getStatus() {
    return status;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookLogMetadataResponse webhookLogMetadataResponse = (WebhookLogMetadataResponse) o;
    return Objects.equals(this.body, webhookLogMetadataResponse.body) &&
        Objects.equals(this.headers, webhookLogMetadataResponse.headers) &&
        Objects.equals(this.status, webhookLogMetadataResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(body, headers, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookLogMetadataResponse {\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

